# Generated by Django 5.1.6 on 2025-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('health_status', models.TextField()),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('date_taken_in', models.DateField()),
            ],
        ),
    ]
