# Generated by Django 5.1.6 on 2025-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('current_pets', models.ManyToManyField(blank=True, to='foster.pet')),
            ],
        ),
    ]
